### DISCUSSION TITLE
Sending movement / Waypoint Commands through topics/services

### DISCUSSION THREAD

**Discussion by arihantpandey** [bdaiinstitute/spot_ros2#483] [General]
Hi,

What is the syntax for sending local waypoint commands through available ros2 interfaces?
I have tried sending 

```
ros2 topic pub /body_pose geometry_msgs/Pose "position:
  x: 1.0
  y: 0.0
  z: 0.0"
```

and the robot does not respond at all. 

I have also tried sending 
```
ros2 topic pub /cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.3" -r 10
``` 
and while the robot does seem to respond to the command, the movement can be best described as "hesitant" and jerky. I suspect I am doing something wrong!

On a similar note, I noticed an available service called robot_command, is there documentation on how I can use this service to construct more complex commands? Would commands sent through this interface block until completed, or only block until the request is received?
