### ISSUE TITLE
Trying to command the robot while motors are locked out causes `EstoppedError`

### ISSUE THREAD

**Issue by JacobJBeck** [bdaiinstitute/spot_ros2#190]
I spent some time trying to run `ros2 run simple_arm_motion arm_simple` and kept getting `Unable to power on robot message was Exception while powering on: bosdyn.api.PowerCommandResponse (EstoppedError): Cannot power on while estopped; inspect EStopState for more info.` 

Looking at the `/status/estop` topic showed all E-stops enabled.
```
estop_states:
- header:
    stamp:
      sec: 1700063619
      nanosec: 396916040
    frame_id: ''
  name: hardware_estop
  type: 1
  state: 2
  state_description: ''
- header:
    stamp:
      sec: 1700063619
      nanosec: 396916040
    frame_id: ''
  name: payload_estop
  type: 1
  state: 2
  state_description: ''
- header:
    stamp:
      sec: 1700063619
      nanosec: 396916040
    frame_id: ''
  name: software_estop
  type: 2
  state: 2
  state_description: ''
```

So, I was confused for a while about what was wrong. Turns out this was caused by the motor lockout button not being pressed when I powered Spot on. It would be nice if the lockout status was shown here as well, or a different error was raised for clarity.

However, based on my quick scan of the Spot SDK, it doesn't seem possible to get the lockout status, so this may not be possible without changes upstream.
